using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CrudBucketMVC.DataAccess;
using CrudBucketMVC.Models;

namespace CrudBucketMVC.Controllers
{
    public class TownsController : Controller
    {
        private readonly CrudBucketContext _context;

        public TownsController(CrudBucketContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var towns = _context.Towns;
            return View(towns);
        }

        // GET: /Towns/New
        public IActionResult New()
        {
            return View();
        }

        // GET: /Towns/1
        [Route("Towns/{id:int}")]
        public IActionResult Show(int id)
        {
            var town = _context.Towns.Find(id);

            return View(town);
        }

    //    // POST: /Movies
    //    [HttpPost]
    //    public IActionResult Index(Movie movie)
    //    {
    //        //Take the movie sent in the request and save it to the database
    //        _context.Movies.Add(movie);
    //        _context.SaveChanges();

    //        // The id generated by the database is now on the object we added to the context
    //        var newMovieId = movie.Id;

    //        // Redirect to our route /movies/show and pass in the newMovieId for the id parameter
    //        return RedirectToAction("show", new { id = newMovieId });
    //    }
    }
}
